sample_rate: 16000
log_prediction: true
ctc_reduction: mean_volume
skip_nan_grad: false
train_ds:
  manifest_filepath: manifests/train_dur.json
  sample_rate: 16000
  batch_size: 32
  shuffle: true
  num_workers: 8
  pin_memory: true
  max_duration: 16.7
  min_duration: 0.2
  is_tarred: false
  tarred_audio_filepaths: null
  shuffle_n: 2048
  bucketing_strategy: fully_randomized
  bucketing_batch_size: null
  augmentor:
    speed:
      prob: 0.4
      sr: 16000
      resample_type: kaiser_best
      min_speed_rate: 0.9
      max_speed_rate: 1.1
validation_ds:
  manifest_filepath: manifests/val_dur.json
  sample_rate: 16000
  batch_size: 16
  shuffle: false
  use_start_end_token: false
  num_workers: 8
  pin_memory: true
test_ds:
  manifest_filepath: null
  sample_rate: 16000
  batch_size: 16
  shuffle: false
  use_start_end_token: false
  num_workers: 8
  pin_memory: true
tokenizer:
  dir: tokenizers/swahili_spe_unigram_v1024_max_5/
  type: bpe
  model_path: nemo:27cf53b58eb44c6f9412bf9e7d4548a9_tokenizer.model
  vocab_path: nemo:804a79a4e50e4253b1351ce5ff24e293_vocab.txt
  spe_tokenizer_vocab: nemo:c3291d4a17cd4af6841d28886072e884_tokenizer.vocab
preprocessor:
  _target_: nemo.collections.asr.modules.AudioToMelSpectrogramPreprocessor
  sample_rate: 16000
  normalize: per_feature
  window_size: 0.025
  window_stride: 0.01
  window: hann
  features: 80
  n_fft: 512
  log: true
  frame_splicing: 1
  dither: 1.0e-05
  pad_to: 0
  pad_value: 0.0
spec_augment:
  _target_: nemo.collections.asr.modules.SpectrogramAugmentation
  freq_masks: 2
  time_masks: 10
  freq_width: 27
  time_width: 0.05
encoder:
  _target_: nemo.collections.asr.modules.ConformerEncoder
  feat_in: 80
  feat_out: -1
  n_layers: 18
  d_model: 512
  subsampling: dw_striding
  subsampling_factor: 8
  subsampling_conv_channels: 256
  causal_downsampling: false
  ff_expansion_factor: 4
  self_attention_model: rel_pos
  n_heads: 8
  att_context_size:
  - -1
  - -1
  att_context_style: regular
  xscaling: true
  untie_biases: true
  pos_emb_max_len: 5000
  use_pytorch_sdpa: false
  use_pytorch_sdpa_backends: []
  conv_kernel_size: 9
  conv_norm_type: batch_norm
  conv_context_size: null
  dropout: 0.1
  dropout_pre_encoder: 0.1
  dropout_emb: 0.0
  dropout_att: 0.1
  stochastic_depth_drop_prob: 0.0
  stochastic_depth_mode: linear
  stochastic_depth_start_layer: 1
decoder:
  _target_: nemo.collections.asr.modules.ConvASRDecoder
  feat_in: 512
  num_classes: 1024
  vocabulary:
  - <unk>
  - ▁
  - a
  - ▁ya
  - ▁wa
  - ▁na
  - ka
  - ▁ku
  - ▁m
  - ▁ma
  - ▁u
  - i
  - ni
  - ▁kwa
  - o
  - ▁k
  - ▁ki
  - ▁ni
  - li
  - ▁kati
  - e
  - d
  - ▁ali
  - wa
  - na
  - b
  - f
  - si
  - u
  - ▁za
  - kuwa
  - c
  - ▁la
  - ri
  - ki
  - zi
  - ma
  - ji
  - ra
  - ▁vi
  - ti
  - s
  - ▁hu
  - ko
  - ▁cha
  - 'n'
  - ta
  - le
  - te
  - m
  - ▁wana
  - ▁mi
  - po
  - la
  - ▁s
  - ba
  - sha
  - fu
  - t
  - ▁nchi
  - mba
  - ▁ili
  - ▁kama
  - za
  - wenye
  - ▁ha
  - '3'
  - '4'
  - ▁ina
  - we
  - ku
  - r
  - ▁wali
  - '7'
  - kubwa
  - ha
  - sa
  - fa
  - ▁pia
  - '5'
  - '0'
  - tu
  - k
  - ▁kuwa
  - ▁moja
  - pa
  - ru
  - isha
  - kana
  - me
  - mbali
  - ▁ana
  - zo
  - mu
  - ▁yake
  - da
  - to
  - '8'
  - di
  - ▁mwa
  - ngine
  - ▁sana
  - moja
  - ja
  - nga
  - ▁amba
  - ▁kuto
  - kati
  - '9'
  - mi
  - hi
  - weza
  - ya
  - ▁vya
  - '6'
  - re
  - ke
  - ga
  - nda
  - ▁watu
  - '2'
  - ani
  - ro
  - lo
  - cha
  - ▁pa
  - pi
  - _
  - mbo
  - bu
  - yo
  - taifa
  - ▁kuna
  - zaidi
  - l
  - ▁n
  - '1'
  - ye
  - ▁hii
  - ▁tan
  - ▁hiyo
  - ▁mia
  - zania
  - g
  - ne
  - vu
  - ▁elfu
  - mbili
  - fanya
  - ▁una
  - ▁au
  - ▁ta
  - ▁afri
  - ▁tu
  - be
  - ea
  - 'no'
  - mo
  - shi
  - pe
  - wi
  - ▁ba
  - ngo
  - hara
  - cho
  - ehemu
  - ▁sa
  - ▁wake
  - 'y'
  - go
  - wengi
  - h
  - baada
  - ▁si
  - ▁mara
  - ▁laki
  - sema
  - se
  - ▁ame
  - ini
  - pata
  - ▁zina
  - ▁mash
  - che
  - ▁hata
  - nya
  - kali
  - p
  - ndo
  - ▁maji
  - hivyo
  - ana
  - ndi
  - nyama
  - ishi
  - ngu
  - vyo
  - onjwa
  - mwaka
  - ariki
  - wanza
  - ▁kila
  - ▁huo
  - lugha
  - ▁nyi
  - lu
  - tumia
  - ▁mji
  - shiri
  - lia
  - endel
  - 'on'
  - pati
  - ▁hadi
  - nu
  - ho
  - ge
  - bo
  - ▁me
  - ▁siku
  - ▁ime
  - gu
  - ▁kumi
  - ▁hasa
  - ▁ja
  - ▁hali
  - mani
  - de
  - ▁tisa
  - ▁uli
  - ▁hi
  - anza
  - ▁juu
  - je
  - ▁eneo
  - j
  - vi
  - mbi
  - ndani
  - ▁kazi
  - pande
  - su
  - fauti
  - jeshi
  - ▁ug
  - ▁mkuu
  - bari
  - mp
  - mbe
  - ▁seri
  - liwa
  - nge
  - usini
  - uhimu
  - ▁bara
  - tokea
  - ▁saba
  - ▁tatu
  - ▁zili
  - shind
  - ano
  - aribu
  - ongoz
  - juli
  - ▁w
  - ▁lina
  - ▁rais
  - sw
  - ▁huu
  - dunia
  - dogo
  - tanga
  - ▁kuu
  - cheza
  - aeneo
  - aribi
  - ereza
  - an
  - ▁to
  - ona
  - fadhi
  - ▁aki
  - ▁vita
  - so
  - ▁hawa
  - ▁baad
  - ▁lili
  - tawal
  - ▁jina
  - sho
  - kundi
  - ▁sasa
  - ▁hilo
  - yingi
  - hu
  - asili
  - ju
  - nde
  - va
  - toka
  - kenya
  - kwa
  - ▁we
  - nzi
  - ▁0
  - askaz
  - ▁mkoa
  - ▁kuli
  - fe
  - toto
  - chini
  - gi
  - heshi
  - w
  - kula
  - aji
  - rini
  - damu
  - ▁aina
  - ▁mar
  - ongez
  - ▁nyum
  - ▁ny
  - ▁asi
  - ▁his
  - ng
  - miwa
  - shu
  - tangu
  - toria
  - yenye
  - ngi
  - ganda
  - ▁tano
  - husi
  - ▁bi
  - ▁duni
  - ▁mtu
  - husu
  - anga
  - wili
  - fiki
  - fuata
  - waida
  - fem
  - iwa
  - kazi
  - ▁mat
  - he
  - ▁baha
  - ▁wao
  - sabab
  - ia
  - ▁wame
  - ▁haku
  - taji
  - chumi
  - sta
  - ishwa
  - ▁mwi
  - rangi
  - ▁sita
  - chu
  - ita
  - itwa
  - mbu
  - zuri
  - jiji
  - pu
  - kabil
  - iliyo
  - jamii
  - jerum
  - ▁muda
  - chi
  - en
  - yu
  - ▁iko
  - ▁nne
  - ▁njia
  - rehe
  - ▁mu
  - atifu
  - ekani
  - ▁hayo
  - ▁huwa
  - ilaya
  - ▁kale
  - ▁bu
  - in
  - shwa
  - el
  - ▁kuji
  - zwa
  - ▁timu
  - ▁yao
  - ▁us
  - ▁aka
  - ▁hili
  - ilima
  - ▁bila
  - mwezi
  - she
  - ▁mazi
  - ondo
  - ▁wote
  - ingi
  - ▁huko
  - ▁zote
  - anz
  - ika
  - chang
  - ahili
  - ▁vile
  - ▁nane
  - zungu
  - voice
  - ▁comm
  - badil
  - risto
  - shule
  - kongo
  - talii
  - '38'
  - ambu
  - abisa
  - ▁sw
  - ▁ishi
  - ▁waki
  - ▁bias
  - tumik
  - saidi
  - ▁leo
  - mengi
  - chama
  - ▁haya
  - ▁nje
  - arufu
  - ▁pili
  - dhi
  - ulaya
  - '57'
  - ▁uta
  - anisa
  - ▁hizi
  - hami
  - ▁mto
  - aliye
  - '59'
  - ngwa
  - singi
  - rusi
  - siasa
  - ria
  - ▁uing
  - pindi
  - miaka
  - kiwa
  - ze
  - taka
  - ▁mag
  - ▁al
  - ▁yote
  - chuku
  - ▁twen
  - wahi
  - ▁uch
  - ▁hapo
  - fasi
  - '12'
  - '68'
  - ▁magh
  - ▁hizo
  - ▁dar
  - '83'
  - oliki
  - ▁mtak
  - mili
  - th
  - pekee
  - jana
  - viazi
  - ties
  - demok
  - '58'
  - andik
  - inayo
  - '20'
  - kuu
  - ▁yeye
  - hali
  - ▁kisw
  - pita
  - kata
  - ndege
  - mbele
  - ▁uk
  - rasia
  - ▁zake
  - mhuri
  - nchi
  - teng
  - thi
  - idadi
  - mwana
  - adhaa
  - nzo
  - ce
  - shaji
  - ▁bora
  - ▁haki
  - ▁v
  - oneka
  - walio
  - ee
  - ababu
  - kabla
  - milia
  - ▁hao
  - fanyi
  - tatu
  - '82'
  - ingia
  - zibar
  - ▁ndio
  - bb
  - liyo
  - ▁zao
  - ajili
  - mlima
  - alama
  - ▁ziwa
  - mpaka
  - pwani
  - ngozi
  - hauri
  - '07'
  - ▁zan
  - wake
  - lioni
  - soma
  - ▁mama
  - ngira
  - ▁ufa
  - elimu
  - '97'
  - jimbo
  - ▁kima
  - rudi
  - pitia
  - ghuli
  - ziri
  - ▁hapa
  - amini
  - ▁mada
  - '64'
  - jumla
  - heria
  - toa
  - uhuru
  - ▁hivi
  - iko
  - ▁bina
  - bd
  - ▁hewa
  - kumbu
  - '52'
  - dc
  - penda
  - pungu
  - bara
  - weka
  - ambao
  - nyika
  - ▁tena
  - dhidi
  - zaliw
  - '32'
  - '02'
  - safi
  - '39'
  - ▁dha
  - liko
  - ▁tuna
  - lishe
  - inine
  - mfano
  - '13'
  - kutan
  - zima
  - ndu
  - ▁chuo
  - ▁baba
  - aduni
  - nayo
  - wisho
  - nywa
  - '71'
  - akiwa
  - gemea
  - pishi
  - ▁iki
  - '60'
  - limu
  - '28'
  - athir
  - bunge
  - '50'
  - limia
  - jua
  - ▁ulio
  - onye
  - '37'
  - hindi
  - doksi
  - nyo
  - nja
  - rtho
  - ▁ume
  - mita
  - ▁kum
  - '99'
  - zu
  - ▁mpya
  - ▁tak
  - ▁dali
  - '14'
  - fika
  - '53'
  - '74'
  - slamu
  - ndiyo
  - mfumo
  - kiasi
  - weze
  - '62'
  - oloni
  - ▁kitu
  - rasmi
  - '17'
  - '96'
  - ▁lake
  - lewa
  - ransa
  - enda
  - ilimo
  - bc
  - ff
  - shamb
  - gombe
  - '73'
  - wango
  - df
  - nne
  - '42'
  - piga
  - '65'
  - '16'
  - '61'
  - wenda
  - '49'
  - makao
  - '81'
  - pewa
  - '06'
  - falme
  - adini
  - uziki
  - masai
  - eleke
  - '84'
  - ▁dini
  - nzani
  - jumui
  - kombe
  - ndari
  - gano
  - '04'
  - nguvu
  - moyo
  - '92'
  - '76'
  - chezo
  - makuu
  - aguzi
  - cc
  - umizi
  - '46'
  - v
  - eneza
  - afuta
  - atizo
  - hatua
  - ▁lime
  - erere
  - yari
  - '34'
  - '40'
  - simam
  - nyota
  - tano
  - ▁dola
  - iongo
  - isiwa
  - ve
  - '78'
  - tambu
  - pelek
  - ▁es
  - unga
  - fundi
  - arifa
  - ▁siti
  - anzia
  - uwezo
  - '56'
  - '41'
  - '86'
  - '55'
  - thela
  - '87'
  - kikuu
  - gumu
  - ▁huku
  - arabu
  - ▁kifo
  - wezi
  - chake
  - ▁mch
  - ▁afya
  - ▁juma
  - '22'
  - ▁bado
  - thini
  - alaam
  - '10'
  - ungu
  - jenga
  - mungu
  - deleo
  - ▁dawa
  - '11'
  - '01'
  - '91'
  - kweli
  - ▁utam
  - zazi
  - miguu
  - hakik
  - rwand
  - pango
  - lmas
  - '18'
  - amua
  - ▁mapi
  - ikiwa
  - tumwa
  - hibit
  - mrefu
  - china
  - '69'
  - '09'
  - hicho
  - pigan
  - ▁maen
  - chagu
  - ▁huyo
  - '72'
  - kadha
  - aunti
  - aalum
  - ▁tisi
  - '93'
  - wanja
  - ardhi
  - alamu
  - ▁tam
  - '21'
  - '90'
  - '98'
  - lojia
  - geni
  - '36'
  - eleza
  - mtoto
  - '63'
  - hudi
  - tabia
  - ndogo
  - leta
  - '15'
  - kubal
  - ▁ata
  - ▁kat
  - mjini
  - ▁co
  - afiti
  - liano
  - jinsi
  - ▁nye
  - abila
  - baini
  - baki
  - ▁mvua
  - z
  - dishi
  - msini
  - ngana
  - faham
  - funga
  - nzuri
  - fedha
  - frika
  - nduzi
  - rahis
  - suala
  - ▁them
  - imar
  - tazam
  - riban
  - ▁huto
  - awali
  - samba
  - duma
  - mpira
  - tibu
  - uaji
  - bidha
  - mbinu
  - tumiw
  - aneno
  - jambo
  - panda
  - uwepo
  - wakat
  - ▁ful
  - dudu
  - ▁sabi
  - wingi
  - lengo
  - sauti
  - uhuri
  - mpuni
  - ▁ulim
  - ▁soka
  - mlaka
  - mwili
  - hama
  - jibu
  - ▁chum
  - namna
  - ▁zime
  - '29'
  - uawa
  - pania
  - yansi
  - ▁umri
  - ▁pep
  - pende
  - pamba
  - bias
  - ▁amin
  - ▁joto
  - ▁neno
  - maliz
  - ▁raia
  - vutio
  - ndiye
  - benki
  - vingi
  - ngoro
  - jengo
  - mnamo
  - ▁muun
  - afiri
  - afari
  - ikosi
  - kulim
  - tolew
  - pokea
  - ifugo
  - kimbi
  - tukio
  - geria
  - kundu
  - wanzo
  - picha
  - ilaha
  - njaro
  - wengu
  - ▁yetu
  - karne
  - ▁nusu
  - pembe
  - bonde
  - namke
  - visiw
  - arume
  - jumbe
  - funzi
  - ulizi
  - tokeo
  - dumu
  - ▁huyu
  - isitu
  - ichwa
  - funza
  - fungu
  - ▁moto
  - ▁wiki
  - lenye
  - ▁pro
  - isasa
  - afisa
  - kihis
  - ungan
  - takiw
  - kizwa
  - ugaji
  - orodh
  - mkono
  - mbwa
  - ▁soko
  - njo
  - asisi
  - sahau
  - nyiko
  - kamat
  - kiliz
  - ukumu
  - usiku
  - ▁inga
  - ▁madh
  - kiing
  - x
  - zuia
  - yeupe
  - ▁kote
  - nafsi
  - ofisi
  - ▁bei
  - oyote
  - saada
  - mikoa
  - asomo
  - yeusi
  - sukum
  - msitu
  - hesab
  - maan
  - furah
  - urefu
  - penzi
  - vutia
  - kadir
  - zenye
  - misri
  - wakil
  - miezi
  - ▁homa
  - razil
  - mimea
  - fuati
  - jengw
  - wenza
  - ▁fila
  - tajwa
  - petro
  - redio
  - lbamu
  - kimwi
  - tafut
  - sekta
  - ukari
  - jacob
  - ahidi
  - guar
  - adhim
  - bwana
  - fanik
  - amuzi
  - sult
  - land
  - ▁sere
  - andam
  - diola
  - ▁mzee
  - q
  - â
  - ó
  - μ
  - ọ
  - é
  - ː
  - ú
  - ø
  - ụ
  - í
  - á
  - ã
  - ü
  - ë
  - ô
  - ũ
  - ö
  - ạ
  - ñ
  - ū
  - è
  - š
  - ç
  - î
  - ā
  - ą
  - ʿ
  - ı
  - ł
  - å
  - ا
  - à
  - ê
  - ⁄
  - ï
  - י
interctc:
  loss_weights: []
  apply_at_layers: []
optim:
  name: adamw
  lr: 0.001
  betas:
  - 0.9
  - 0.98
  weight_decay: 0.001
  sched:
    name: CosineAnnealing
    warmup_steps: 15000
    warmup_ratio: null
    min_lr: 0.0001
target: nemo.collections.asr.models.ctc_bpe_models.EncDecCTCModelBPE
nemo_version: 2.4.1
decoding:
  strategy: greedy_batch
  preserve_alignments: null
  compute_timestamps: null
  word_seperator: ' '
  segment_seperators:
  - .
  - '!'
  - '?'
  segment_gap_threshold: null
  ctc_timestamp_type: all
  batch_dim_index: 0
  greedy:
    preserve_alignments: false
    compute_timestamps: false
    preserve_frame_confidence: false
    confidence_method_cfg:
      name: entropy
      entropy_type: tsallis
      alpha: 0.33
      entropy_norm: exp
      temperature: DEPRECATED
    ngram_lm_model: null
    ngram_lm_alpha: 0.0
    allow_cuda_graphs: true
  beam:
    beam_size: 4
    search_type: default
    preserve_alignments: false
    compute_timestamps: false
    return_best_hypothesis: true
    allow_cuda_graphs: true
    beam_alpha: null
    beam_beta: 1.0
    beam_threshold: 20.0
    kenlm_path: null
    ngram_lm_alpha: 1.0
    ngram_lm_model: null
    flashlight_cfg:
      lexicon_path: null
      boost_path: null
      beam_size_token: 16
      beam_threshold: 20.0
      unk_weight: -.inf
      sil_weight: 0.0
    pyctcdecode_cfg:
      beam_prune_logp: -10.0
      token_min_logp: -5.0
      prune_history: false
      hotwords: null
      hotword_weight: 10.0
  wfst:
    beam_size: 4
    search_type: riva
    return_best_hypothesis: true
    preserve_alignments: false
    compute_timestamps: false
    decoding_mode: nbest
    open_vocabulary_decoding: false
    beam_width: 10.0
    lm_weight: 1.0
    device: cuda
    arpa_lm_path: null
    wfst_lm_path: null
    riva_decoding_cfg: {}
    k2_decoding_cfg:
      search_beam: 20.0
      output_beam: 10.0
      min_active_states: 30
      max_active_states: 10000
  confidence_cfg:
    preserve_frame_confidence: false
    preserve_token_confidence: false
    preserve_word_confidence: false
    exclude_blank: true
    aggregation: min
    tdt_include_duration: false
    method_cfg:
      name: entropy
      entropy_type: tsallis
      alpha: 0.33
      entropy_norm: exp
      temperature: DEPRECATED
  temperature: 1.0
